FROM openjdk:17.0.1-jdk-slim

WORKDIR /app
COPY /build/libs/preorder-0.0.1-SNAPSHOT.jar /app/app.jar
COPY /scouter/agent.java /app/scouter/agent.java

EXPOSE 8084

ENTRYPOINT ["java", "-javaagent:scouter/agent.java/scouter.agent.jar" ,"-jar", "app.jar"]